name: fluwx
description: A Flutter plugin allowing developers to share or pay with natvie android & iOS Wechat SDKs.
version: 1.1.3
author: JarvanMo <jarvan.mo@gmail.com>
homepage: https://github.com/JarvanMo/fluwx

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.jarvan.fluwx
    pluginClass: FluwxPlugin